// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ncorep.Models;

namespace MultiLevelEncryptedEshop.Models;

public partial class Address : BaseEntity
{
    public string City { get; set; }

    public string StreetAddress { get; set; }

    public string ExactAddress { get; set; }

    public string PostalCode { get; set; }

    public string UserId { get; set; }
    public virtual User User { get; set; }
}